name: Rick Such
favicon: null
layout_spectrum: 0.98684
typography_spectrum: 0.6219241365324706
title: Rick Such Voiceover + Assorted Interests
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#110c10'
    - '#275674'
    - '#bfaca0'
    - '#f8eadc'
    - '#923729'
  brandStrength: 0.2472414644435048
  lightness: 0.8751103437971324
  saturation: 0.2438219643663615
  rhythmicContrast: 0.31878700316883624
purpose: []
